Bukarev lesson 4
eugene-okulik/Bukarev pull request #3
Opened 2024-07-23 12:08 UTC by ABVSVL

2024-07-23 15:12 UTC, eugene-okulik requested changes
Всё отлично, но одну проверку на внимательность не прошел.

2024-07-23 15:12 UTC, eugene-okulik commented on homework/Lesson4/my_dict.py
> +my_dict['dict']['i am a tuple'] = 'test_add_new_value'
В задании было:

> добавьте элемент с ключом ('i am a tuple',) и любым значением

У тебя выполнено как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

`('i am a tuple',) ` - кортеж с одним элементом. И именно это и должно быть ключом. Сейчас ключ - строка `'i am a tuple'`

2024-07-24 04:25 UTC, ABVSVL commented on homework/Lesson4/my_dict.py
> +my_dict['dict']['i am a tuple'] = 'test_add_new_value'
Да я не так понял... я думал надо добавить просто строку в словарик....

Для того, что хранится под ключом ‘dict’:
добавьте элемент с ключом ('i am a tuple',) и любым значением
удалите какой-нибудь элемент

**Возможно если бы было описание** 

Для того, что хранится под ключом ‘dict’:
добавьте элемент (**тип элемента Tuple**) с ключом ('i am a tuple',) и любым значением

2024-07-24 07:45 UTC, eugene-okulik requested changes

2024-07-24 07:45 UTC, eugene-okulik commented on homework/Lesson4/my_dict.py
> +my_dict['dict']['i am a tuple'] = ('test_add_new_value', )
Теперь у тебя значение `('test_add_new_value', )` , а по заданию, `('test_add_new_value', )` должно быть ключом. Ключ у тебя всё еще строка `'i am a tuple'`

2024-07-24 08:39 UTC, eugene-okulik requested changes

2024-07-24 08:39 UTC, eugene-okulik commented on homework/Lesson4/my_dict.py
> +my_dict['dict']['test_add_new_value'] = ('i am a tuple', )
сейчас у тебя под ключом` 'test_add_new_value'` (строка) хранится значение `('i am a tuple', )`  
А должно под ключом `('i am a tuple', )` храниться абсолютно любое значение  
Повторю, что ожидается, что ключом будет кортеж с одним элементом. Сейчас ключом является строка.

2024-07-24 08:40 UTC, ABVSVL commented on homework/Lesson4/my_dict.py
> +my_dict['dict']['i am a tuple'] = ('test_add_new_value', )
Если я правильно понял, мне надо их поменять местами ? 
my_dict['dict']['test_add_new_value'] = ('i am a tuple', )

2024-07-24 09:15 UTC, ABVSVL commented
Евгений посмотри еще разок...  =))
и еще у меня вот такой вопрос как ты видишьь что там была строка ? 

Сейчас я пересмотрел еще раз ролик и все ( как мне кажется) я поправил =))

У меня вопрос, как я могу понять что в моем Словаре есть ключ который имеет определенный тип ? 
я думал это можно узнать вот так:
print(type(my_dict['dict']['i am a tuple']))
Но когда я так делаю, я получаю,

C:\Projects\Bukarev\pythonProject1\.venv\Scripts\python.exe C:\Projects\Bukarev\homework\Lesson4\my_dict.py 
Traceback (most recent call last):
  File "C:\Projects\Bukarev\homework\Lesson4\my_dict.py", line 16, in <module>
    print(type(my_dict['dict']['i am a tuple']))
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
**KeyError: 'i am a tuple'**

2024-07-24 09:19 UTC, eugene-okulik approved these changes
Ура!

2024-07-24 09:19 UTC, merged

2024-07-24 09:51 UTC, ABVSVL commented
Пришлось пересмотреть еще раз ролик =))

2024-07-24 16:37 UTC, eugene-okulik commented
> Пришлось пересмотреть еще раз ролик =))

Здачит, цель достигнута )))