Lesson_10
eugene-okulik/Bukarev pull request #9
Opened 2024-08-08 06:37 UTC by ABVSVL

2024-08-08 10:08 UTC, eugene-okulik requested changes
Если что-то прям совсем не понятно - пиши, будем разбираться.

2024-08-08 10:08 UTC, eugene-okulik commented on homework/lesson_10/File_3.py
> +            print(f'функция "repeat_me" вызывалась {count1} раз: ', *args * count1, sep='\n')
Здесь ты просто внутри wrapper 2 раза распечатываешь текст, но не вызываешь 2 раза декорируемую функцию.  
По сути, вызвав функцию, ты ее вообще не запустил - у тебя отработал только код декоратора.

2024-08-08 10:08 UTC, eugene-okulik commented on homework/lesson_10/File_4.py
> +    print('Test1')
Содержимое этой функции должно быть таким, как в задании (ну, дописанным только)
```python
if operation == '+':
    return first + second
elif .....
```

2024-08-08 10:08 UTC, eugene-okulik commented on homework/lesson_10/File_4.py
> +            return print(first * second)
В случае, если число меньше нуля, нужно не распечатать первое число, умноженное на второе, а вызвать декорируемую функцию с правильным оператором.  
В этом декораторе ты тоже забыл, что декоратор не заменяет декорируемую функцию, а дополняет её функциональность.

2024-08-08 14:59 UTC, eugene-okulik requested changes

2024-08-08 14:59 UTC, eugene-okulik commented on homework/lesson_10/File_2.py
В file3 хорошо сделал. Осталось еще здесь сделать, чтобы декоратор как-то использовал ту функцию, которую в него передали.

2024-08-08 14:59 UTC, eugene-okulik commented on homework/lesson_10/File_2.py
По сути, здесь подход такой же как в file3, но немного проще.

2024-08-08 15:07 UTC, eugene-okulik commented
Эмм, так ты же еще ничего не изменил после последнего коментария. Или что ты имел ввиду, когда запросил ревью?

2024-08-08 16:40 UTC, ABVSVL commented on homework/lesson_10/File_2.py
я вроде исправлял. И в декораторе поставил принт. Что бы видеть что считается. в декораторе согласно условиям, присваевается значение оператора и потом вызывается функция ( с принтом).
Может я не так понял про последний комментарий? File4 

![image](https://github.com/user-attachments/assets/cbcfd47b-4117-4872-a261-ef26d08c0d3b)

2024-08-08 16:42 UTC, ABVSVL commented on homework/lesson_10/File_2.py
Ну расчитывал, что я исправил в полном объеме все =)

2024-08-08 17:09 UTC, ABVSVL commented
я вроде исправлял. В дикораторе вызывается дикорируемая функция. File4

2024-08-09 03:31 UTC, ABVSVL commented
Если все же я сделал не правильно, я постучусь в личку к тебе

2024-08-09 08:07 UTC, eugene-okulik approved these changes
Да, вот теперь всё ок.

2024-08-09 08:07 UTC, merged